import 'package:get/get.dart';

class PesananController extends GetxController {
  var pesanan = [
    {
      'namaPemesan': 'Budi Setiawan',
      'item': '3',
      'total': 'Rp 48.000',
      'pembayaran': "Tunai",
      'tempat': "Makan di tempat",
      'jumlahPesanan': '5',
    },
    {
      'namaPemesan':
          'Dewi Susanti aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      'item': '2',
      'total': 'Rp 35.000',
      'pembayaran': "QRIS",
      'tempat': "Bungkus",
      'jumlahPesanan': '2',
    },
    {
      'namaPemesan': 'Putra Wijaya',
      'item': '1',
      'total': 'Rp 28.000',
      'pembayaran': "Tunai",
      'tempat': "Bungkus",
      'jumlahPesanan': '1',
    },
    {
      'namaPemesan': 'Sari Rahayu',
      'item': '4',
      'total': 'Rp 60.000',
      'pembayaran': "QRIS",
      'tempat': "Makan di tempat",
      'jumlahPesanan': '3',
    },
    {
      'namaPemesan': 'Adi Santoso',
      'item': '1',
      'total': 'Rp 50.000',
      'pembayaran': "Tunai",
      'tempat': "Bungkus",
      'jumlahPesanan': '1',
    },
    {
      'namaPemesan': 'Dian Fitriani',
      'item': '2',
      'total': 'Rp 30.000',
      'pembayaran': "QRIS",
      'tempat': "Makan di tempat",
      'jumlahPesanan': '2',
    },
    {
      'namaPemesan': 'Rudi Pratama',
      'item': '3',
      'total': 'Rp 42.000',
      'pembayaran': "Tunai",
      'tempat': "Bungkus",
      'jumlahPesanan': '2',
    },
    {
      'namaPemesan': 'Ani Widya',
      'item': '2',
      'total': 'Rp 25.000',
      'pembayaran': "QRIS",
      'tempat': "Bungkus",
      'jumlahPesanan': '2',
    },
    {
      'namaPemesan': 'Bambang Tri',
      'item': '5',
      'total': 'Rp 70.000',
      'pembayaran': "Tunai",
      'tempat': "Makan di tempat",
      'jumlahPesanan': '4',
    },
    {
      'namaPemesan': 'Eka Putri',
      'item': '3',
      'total': 'Rp 45.000',
      'pembayaran': "QRIS",
      'tempat': "Bungkus",
      'jumlahPesanan': '3',
    },
    {
      'namaPemesan': 'Firman Kurniawan',
      'item': '2',
      'total': 'Rp 32.000',
      'pembayaran': "Tunai",
      'tempat': "Bungkus",
      'jumlahPesanan': '2',
    },
    {
      'namaPemesan': 'Gita Sari',
      'item': '1',
      'total': 'Rp 15.000',
      'pembayaran': "QRIS",
      'tempat': "Makan di tempat",
      'jumlahPesanan': '1',
    },
    {
      'namaPemesan': 'Hendra Gunawan',
      'item': '4',
      'total': 'Rp 55.000',
      'pembayaran': "Tunai",
      'tempat': "Bungkus",
      'jumlahPesanan': '3',
    },
    {
      'namaPemesan': 'Ika Nurhayati',
      'item': '2',
      'total': 'Rp 28.000',
      'pembayaran': "QRIS",
      'tempat': "makan di tempat",
      'jumlahPesanan': '2',
    },
    {
      'namaPemesan': 'Joko Susilo',
      'item': '3',
      'total': 'Rp 40.000',
      'pembayaran': "Tunai",
      'tempat': "bungkus",
      'jumlahPesanan': '2',
    },
    {
      'namaPemesan': 'Kiki Hartanto',
      'item': '2',
      'total': 'Rp 25.000',
      'pembayaran': "QRIS",
      'tempat': "Bungkus",
      'jumlahPesanan': '2',
    },
    {
      'namaPemesan': 'Lia Rahman',
      'item': '1',
      'total': 'Rp 18.000',
      'pembayaran': "Tunai",
      'tempat': "Makan di tempat",
      'jumlahPesanan': '1',
    },
    {
      'namaPemesan': 'Maman Sofyan',
      'item': '4',
      'total': 'Rp 60.000',
      'pembayaran': "QRIS",
      'tempat': "Bungkus",
      'jumlahPesanan': '3',
    },
    {
      'namaPemesan': 'Nadia Indriani',
      'item': '3',
      'total': 'Rp 45.000',
      'pembayaran': "Tunai",
      'tempat': "Makan di tempat",
      'jumlahPesanan': '3',
    },
    {
      'namaPemesan': 'Oki Saputra',
      'item': '2',
      'total': 'Rp 28.000',
      'pembayaran': "QRIS",
      'tempat': "Bungkus",
      'jumlahPesanan': '2',
    },
    {
      'namaPemesan': 'Putri Anggraini',
      'item': '1',
      'total': 'Rp 15.000',
      'pembayaran': "Tunai",
      'tempat': "Bungkus",
      'jumlahPesanan': '1',
    }
  ];

  @override
  void onInit() {
    super.onInit();
  }
}
