import 'package:get/get.dart';

class RekapanController extends GetxController {
  var rekapan = [
    {
      'namaPemesan': 'Budi Setiawan',
      'item': '3',
      'kode': 'M-JN037',
      'total': 'Rp 48.000',
      'pembayaran': "Tunai",
      'tempat': "makan di tempat",
      'jumlahPesanan': '5',
    },
    {
      'namaPemesan': 'Dewi Susanti',
      'item': '2',
      'kode': 'M-JN038',
      'total': 'Rp 35.000',
      'pembayaran': "QRIS",
      'tempat': "bawa pulang",
      'jumlahPesanan': '2',
    },
    {
      'namaPemesan': 'Putra Wijaya',
      'item': '1',
      'kode': 'M-JN039',
      'total': 'Rp 28.000',
      'pembayaran': "Tunai",
      'tempat': "antar",
      'jumlahPesanan': '1',
    },
    {
      'namaPemesan': 'Sari Rahayu',
      'item': '4',
      'kode': 'M-JN040',
      'total': 'Rp 60.000',
      'pembayaran': "QRIS",
      'tempat': "makan di tempat",
      'jumlahPesanan': '3',
    },
    {
      'namaPemesan': 'Adi Santoso',
      'item': '1',
      'kode': 'M-JN041',
      'total': 'Rp 50.000',
      'pembayaran': "Tunai",
      'tempat': "bawa pulang",
      'jumlahPesanan': '1',
    },
    {
      'namaPemesan': 'Dian Fitriani',
      'item': '2',
      'kode': 'M-JN042',
      'total': 'Rp 30.000',
      'pembayaran': "QRIS",
      'tempat': "makan di tempat",
      'jumlahPesanan': '2',
    },
    {
      'namaPemesan': 'Rudi Pratama',
      'item': '3',
      'kode': 'M-JN043',
      'total': 'Rp 42.000',
      'pembayaran': "Tunai",
      'tempat': "antar",
      'jumlahPesanan': '2',
    },
    {
      'namaPemesan': 'Ani Widya',
      'item': '2',
      'kode': 'M-JN044',
      'total': 'Rp 25.000',
      'pembayaran': "QRIS",
      'tempat': "bawa pulang",
      'jumlahPesanan': '2',
    },
    {
      'namaPemesan': 'Bambang Tri',
      'item': '5',
      'kode': 'M-JN045',
      'total': 'Rp 70.000',
      'pembayaran': "Tunai",
      'tempat': "makan di tempat",
      'jumlahPesanan': '4',
    },
    {
      'namaPemesan': 'Eka Putri',
      'item': '3',
      'kode': 'M-JN046',
      'total': 'Rp 45.000',
      'pembayaran': "QRIS",
      'tempat': "bawa pulang",
      'jumlahPesanan': '3',
    },
    {
      'namaPemesan': 'Firman Kurniawan',
      'item': '2',
      'kode': 'M-JN047',
      'total': 'Rp 32.000',
      'pembayaran': "Tunai",
      'tempat': "antar",
      'jumlahPesanan': '2',
    },
    {
      'namaPemesan': 'Gita Sari',
      'item': '1',
      'kode': 'M-JN048',
      'total': 'Rp 15.000',
      'pembayaran': "QRIS",
      'tempat': "makan di tempat",
      'jumlahPesanan': '1',
    },
    {
      'namaPemesan': 'Hendra Gunawan',
      'item': '4',
      'kode': 'M-JN049',
      'total': 'Rp 55.000',
      'pembayaran': "Tunai",
      'tempat': "bawa pulang",
      'jumlahPesanan': '3',
    },
    {
      'namaPemesan': 'Ika Nurhayati',
      'item': '2',
      'kode': 'M-JN050',
      'total': 'Rp 28.000',
      'pembayaran': "QRIS",
      'tempat': "makan di tempat",
      'jumlahPesanan': '2',
    },
    {
      'namaPemesan': 'Joko Susilo',
      'item': '3',
      'kode': 'M-JN051',
      'total': 'Rp 40.000',
      'pembayaran': "Tunai",
      'tempat': "antar",
      'jumlahPesanan': '2',
    },
    {
      'namaPemesan': 'Kiki Hartanto',
      'item': '2',
      'kode': 'M-JN052',
      'total': 'Rp 25.000',
      'pembayaran': "QRIS",
      'tempat': "bawa pulang",
      'jumlahPesanan': '2',
    },
    {
      'namaPemesan': 'Lia Rahman',
      'item': '1',
      'kode': 'M-JN053',
      'total': 'Rp 18.000',
      'pembayaran': "Tunai",
      'tempat': "makan di tempat",
      'jumlahPesanan': '1',
    },
    {
      'namaPemesan': 'Maman Sofyan',
      'item': '4',
      'kode': 'M-JN054',
      'total': 'Rp 60.000',
      'pembayaran': "QRIS",
      'tempat': "bawa pulang",
      'jumlahPesanan': '3',
    },
    {
      'namaPemesan': 'Nadia Indriani',
      'item': '3',
      'kode': 'M-JN055',
      'total': 'Rp 45.000',
      'pembayaran': "Tunai",
      'tempat': "makan di tempat",
      'jumlahPesanan': '3',
    },
    {
      'namaPemesan': 'Oki Saputra',
      'item': '2',
      'kode': 'M-JN056',
      'total': 'Rp 28.000',
      'pembayaran': "QRIS",
      'tempat': "antar",
      'jumlahPesanan': '2',
    },
    {
      'namaPemesan': 'Putri Anggraini',
      'item': '1',
      'kode': 'M-JN057',
      'total': 'Rp 15.000',
      'pembayaran': "Tunai",
      'tempat': "bawa pulang",
      'jumlahPesanan': '1',
    }
  ];

  @override
  void onInit() {
    super.onInit();
  }
}
